<?php
/* 
 * @author: YuSongYang
 * @date: 2010-12-30
 */
class sys_conf
{

//本机
    public static $DBHOST = "localhost";
    public static $DBUSER = "root";
    public static $DBPASSWORD = "";
    public static $DBNAME = "test";
    public static $TABUSER = "user";

    //本机
//    public static $DBHOST = "192.168.1.117";
//    public static $DBUSER = "root";
//    public static $DBPASSWORD = "";
//    public static $DBNAME = "test";
//    public static $TABUSER = "user";
}

?>